version: '3.9'

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    ports:
      - "8000:8000"
    depends_on:
      - clamav
    environment:
      - CLAMAV_HOST=localhost
      - CLAMAV_PORT=3310

  clamav:
    image: clamav/clamav:latest # Pull the latest version from Docker Hub
    container_name: clamav
    ports:
      - "3310:3310"
