# Base Python image
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Install required Python libraries
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy the Python script
COPY virus_scan.py .

# Run the Python app
CMD ["python", "virus_scan.py"]
