version: '3.8'
services:
  clamav:
    build:
      context: .
      dockerfile: Dockerfile.clamav
    container_name: clamav
    ports:
      - "3310:3310"

  python_app:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: python_app
    depends_on:
      - clamav
    volumes:
      - .:/app
